#!/bin/bash
# this is a hook from the git-pushups project

GP="[git-pushups/post-push]"

if [ ! -x "$(which countpushup)" > /dev/null ]; then
    echo "$GP Can't count, countpushup missing from PATH"
    exit 0
fi

countpushup $@

