#!/bin/bash
# run this script in a git repo to install the hook

SRC="$HOME/.local/bin"
FILE="$SRC/countpushup_post-commit"

[ -d .git ] || exit 1 # not a git repo
[ -x "$FILE" ] || exit 2 # source file missing

cp "$FILE" .git/hooks/post-commit

